### ISSUE TITLE
Could not load file or assembly System.Fabric.BackupRestore

### ISSUE THREAD

**Issue by chrisdrobison** [Azure/service-fabric-issues#1009]
Could not load file or assembly 'System.Fabric.BackupRestore, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

We are running 6.1.480.9494 of the runtime and 3.0.480 of SDK. We are also targeting .NET Core 2.0. This happens when SF tries to instantiate a stateful service.

**Comment by ashishnegi** [comment]
@chrisdrobison Please update to latest packages runtime `6.2.262` and sdk `3.1.262` and let us know if you still face the problem.

**Comment by raunakpandya** [comment]
Can you also confirm the version of the runtime you are using? This issue should be with v6.2

**Comment by olitomlinson** [comment]
Getting the same issue.

Upgraded my solution to the latest nuget packages.
Works fine when running `6.2` locally
`BackupRestore not found` when running in Azure on `6.1`

**Comment by andrewdmoreno** [comment]
@ashishnegi @raunakpandya Do the above responses no longer apply after the packages have been removed? I don't think updating packages is an option at this time. Any recommendations for others of us that are experiencing this issue?

**Comment by ashishnegi** [comment]
@andrewdmoreno You can downgrade both sdk and runtime to 6.1. We will republish 6.2 version again with the fixes.

**Comment by andrewdmoreno** [comment]
Thanks, I figured that was the only option at this point.

**Comment by hrushib** [comment]
@andrewdmoreno , @olitomlinson This issue is resolved with the above latest runtime (version 6.2.274) and latest SDK packages (version 3.1.274). Please try this combination and revert back in case you face any issue. Refer [6.2 Release Update](https://blogs.msdn.microsoft.com/azureservicefabric/2018/05/14/6-2-release-update/) for further details.

Thanks for reporting this issue and your patience while we were fixing it.

**Comment by jurgensels** [comment]
@hrushib , I have updated to the latest release 6.2.274 and are still getting the same issue where stateful actors does not load/register. 

I have created a new SF project with only 1 actor(default code) to see if there were any issues with my code. Same issue

I get the following:
"Message": "Actor type Actor1.Actor1 registered.",
and then immediately after:
"Message": "ApplicationHostTerminated:   ApplicationId=fabric:/SFtest,  ServiceName=,  ServicePackageName=Actor1Pkg,  ServicePackageActivationId=,  IsExclusive=False,  CodePackageName=Code,  EntryPointType=Exe,  ExeName=Actor1.exe,  ProcessId=13936,  HostId=c1e9353f-d23c-4d85-85cb-4fef5ea64cce,  ExitCode=2148734499,  UnexpectedTermination=True,  StartTime=15:47:40.200589 (22,630.310 MSec). "

In the output window I get 'Skipped loading symbols' on all Dlls

Any ideas??

**Comment by hrushib** [comment]
@jurgensels, I tried to Repro this issue with fresh installation of 6.2.274 runtime and corresponding SDK (3.1.274/6.2.274) but failed to repro the issue. Please ensure that the 6.2.274 is properly installed on your machine and right SDK is used.

**Comment by jurgensels** [comment]
@hrushib , I re-installed Win 10 and VS 2017 with latest SDK and .net core 2.12. Still getting the same issue with default actor code.

**Comment by hrushib** [comment]
@jurgensels, sorry to here that you are still facing issues on clean deployment. 
As mentioned earlier, I do not see any issue with default Actor service with this runtime and SDK. Request you to add further details mentioning exact steps your are following and share the code, if possible. This may help me understand root cause of the issue.
