### ISSUE TITLE
Deploy failed due to FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR

### ISSUE THREAD

**Issue by yuez1989** [Azure/service-fabric-issues#1441]
Hi Service Fabric Issues Team,

This is to report a deployment issue we are having since yesterday. This is Azure Service Fabric on Linux, and our deployment to service fabric host fails with message:

```
2019-02-08T01:58:42.7885017Z Service fabric SDK version: 3.2.176.9494.
2019-02-08T01:58:45.3459201Z Copying application to image store...
2019-02-08T01:58:59.8719769Z Upload to Image Store succeeded
2019-02-08T01:58:59.8719769Z Registering application type...
2019-02-08T01:59:02.1517824Z Register application type started. Use Get-ServiceFabricApplicationType to query for status.
2019-02-08T01:59:02.2298950Z Getting application type...
2019-02-08T01:59:05.2662708Z Getting application type...
2019-02-08T01:59:08.4266426Z ##[warning]Can't find command extension for ##vso[telemetry.command]. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
**2019-02-08T01:59:09.4243270Z ##[error]Exception calling "Invoke" with "1" argument(s): "Failed to register application type. Status: Failed. Details: FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR."**
2019-02-08T01:59:09.4711641Z ##[section]Finishing: Deploy Service Fabric Application
```

Today, we are still not able to deploy, but this time due to timeout. I retried twice and the issue persists.

```
2019-02-08T18:32:26.9318794Z Service fabric SDK version: 3.2.176.9494.
2019-02-08T18:32:29.3694324Z Copying application to image store...
2019-02-08T19:02:41.0987754Z Exception occurred: System.TimeoutException
2019-02-08T19:02:41.0987754Z Retrying upload...
2019-02-08T19:32:51.1148567Z Exception occurred: System.TimeoutException
2019-02-08T19:32:51.1148567Z Retrying upload...
2019-02-08T20:03:01.1468604Z Exception occurred: System.TimeoutException
2019-02-08T20:03:01.2562196Z ##[warning]Can't find command extension for ##vso[telemetry.command]. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2019-02-08T20:03:01.9905963Z ##[error]Operation timed out.
2019-02-08T20:03:02.0374705Z ##[section]Finishing: Deploy Service Fabric Application
```

From the log, it seems to be the issue "Reconfiguration is stuck. Waiting for response from the local replica"
![image](https://user-images.githubusercontent.com/9024790/52513524-28d0d280-2bc0-11e9-9a3c-128a258018b3.png)

Could you please help us find the issue? 

Thank you!

**Comment by oanapl** [comment]
This is most likely due to [Known Issue for Service Fabric Linux Cluster](https://blogs.msdn.microsoft.com/azureservicefabric/2019/02/07/known-issue-for-service-fabric-linux-clusters/?fbclid=IwAR1__okOwA9LF8nv_CymmhNWx0geEUasDEwgBez0MeygkgmU3UgkKrYNbWc). Please try the proposed mitigation and let us know if that solves it.

**Comment by xzhou1111** [comment]
We try the proposed mitigation , redeploy the ARM template. It seams to fix the issue for one deployment.

However it failed the second deployment with the same above error, or the following error. And error is not consistent. Tried redeploy ARM template again, and did not resolve the issue,

Exception while parsing XML file: /mnt/sfroot/IB/131947411644436310/2e0f1ldq.fxx. Check if XML content is well formed by comparing against the service model schema (ServiceFabricServiceModel.xsd) which is shipped with the SDK. By default, the schema file is installed to 'C:\Program Files\Microsoft SDKs\Service Fabric\schemas\ServiceFabricServiceModel.xsd'.
FileName: /mnt/sfroot/IB/131947411644436310/2e0f1ldq.fxx --> InvalidOperationException: There is an error in XML document (0, 0). --> XmlException: Root element is missing.

**Comment by oanapl** [comment]
@xzhou1111 , the first script we published did not disable future updates for the package, so the changes could get overridden. The latest script disables updates with these lines:

```bash
status, output, error = execute_command(["sed -i 's+//\t\"vim\"+\trssh+g' /etc/apt/apt.conf.d/50unattended-upgrades"])
```

Can you check whether you applied the latest script?

**Comment by xzhou1111** [comment]
This must be the reason.  This is the version I use https://gist.githubusercontent.com/mhatreabhay/695a90331c29dcb83ef7d439b394ad5d/raw/77e3f877c2c0cdd160dbbb618b83fd21ee50edd4/rssh_2_4_4-4_sf.py

I will update the ARM template and try it again

**Comment by oanapl** [comment]
@xzhou1111 , did that fix your issues?

**Comment by xzhou1111** [comment]
@oanapl  Thank you for the follow up.

I have two service fabric.

The staging one seams work fine. I tried deploy four times, all works fine now.

The production service fabric has some issue.
1. I deployed ARM template with new py script, success
2. Deploy service fabric, still the same issue
3. Try to deploy ARM template, and failed.
Find out one of instance is stuck on reconfiguration replica, I am trying to restart that instance see if it can fixed.

**Comment by oanapl** [comment]
@mhatreabhay for more help.

**Comment by xzhou1111** [comment]
After deactivate the node that keep having some error, successfully deployed ARM template, and successfully deployed service fabric twice.

So I think the issue is resolved. The broken node I think is node related to the issue, I may just deallocate it.

Thanks @oanapl

**Comment by oanapl** [comment]
Thank you for the update, @xzhou1111 . I will close the issue, feel free to open a new one if you have other issues.
